-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 09:37:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `user_name` VARCHAR(50) NOT NULL COMMENT '이름',
  `user_password` VARCHAR(200) NOT NULL COMMENT 'mysql password 사용',
  `user_birth` VARCHAR(8) NOT NULL COMMENT '생년월일 : 19840503',
  `user_auth` VARCHAR(10) NOT NULL COMMENT '권한 : ROLE_ADMIN, ROLE_USER',
  `user_point` INT NOT NULL DEFAULT 1000000 COMMENT 'default : 1000000',
  `created_at` DATETIME NOT NULL COMMENT '가입 일자',
  `latest_login_at` DATETIME NULL DEFAULT NULL COMMENT '마지막 로그인 일자',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '회원';


-- -----------------------------------------------------
-- Table `addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addresses` (
  `address_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `user_id` VARCHAR(50) NOT NULL,
  `address_name` VARCHAR(50) NOT NULL COMMENT '주소 별칭',
  `zip_code` VARCHAR(5) NOT NULL COMMENT '우편 번호',
  `road_address` VARCHAR(200) NOT NULL COMMENT '도로명 주소',
  `detail_address` VARCHAR(200) NULL,
  `is_default` TINYINT(1) NOT NULL COMMENT '기본 배송지 여부',
  PRIMARY KEY (`address_id`),
  CONSTRAINT `fk_addresses_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '회원 주소';

CREATE INDEX `fk_addresses_users_idx` ON `addresses` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `product_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `product_name` VARCHAR(200) NOT NULL COMMENT '상품명',
  `price` INT NOT NULL,
  `stock` INT NOT NULL COMMENT '재고',
  `thumbnail_image_path` VARCHAR(200) NOT NULL COMMENT '썸네일 이미지 경로\n',
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '상품';


-- -----------------------------------------------------
-- Table `carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carts` (
  `cart_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `user_id` VARCHAR(50) NOT NULL,
  `product_id` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`cart_id`),
  CONSTRAINT `fk_carts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '장바구니'
PACK_KEYS = Default
ROW_FORMAT = Default;

CREATE INDEX `fk_carts_users1_idx` ON `carts` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_carts_products1_idx` ON `carts` (`product_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `uk_user_product` ON `carts` (`user_id` ASC, `product_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `user_id` VARCHAR(50) NOT NULL,
  `total_amount` INT NOT NULL COMMENT '주문 금액',
  `earn_point` INT NOT NULL COMMENT '포인트 적립 (주문 금액의 10%)',
  `created_at` DATETIME NOT NULL COMMENT '주문 일자',
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '주문';

CREATE INDEX `fk_orders_users1_idx` ON `orders` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `images` (
  `image_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `product_id` VARCHAR(50) NOT NULL,
  `image_path` VARCHAR(200) NOT NULL COMMENT '이미지 경로',
  PRIMARY KEY (`image_id`),
  CONSTRAINT `fk_images_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '상세 이미지';

CREATE INDEX `fk_images_products1_idx` ON `images` (`product_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `category_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `category_name` VARCHAR(50) NOT NULL COMMENT '카테고리명',
  `sort_order` TINYINT(1) NOT NULL COMMENT '정렬순서',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '카테고리';


-- -----------------------------------------------------
-- Table `points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `points` (
  `point_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `user_id` VARCHAR(50) NOT NULL,
  `order_id` VARCHAR(50) NULL,
  `amount` INT NOT NULL COMMENT '사용/적립 포인트',
  `reason` VARCHAR(50) NOT NULL COMMENT '사용/적립 내용',
  `created_at` DATETIME NOT NULL COMMENT '사용/적립 일자',
  PRIMARY KEY (`point_id`),
  CONSTRAINT `fk_points_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_points_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '포인트 사용 내역';

CREATE INDEX `fk_points_users1_idx` ON `points` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_points_orders1_idx` ON `points` (`order_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_category` (
  `product_id` VARCHAR(50) NOT NULL,
  `category_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  CONSTRAINT `fk_product_category_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_category_products1_idx` ON `product_category` (`product_id` ASC) VISIBLE;

CREATE INDEX `fk_product_category_categories1_idx` ON `product_category` (`category_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_details` (
  `order_detail_id` VARCHAR(50) NOT NULL COMMENT '아이디',
  `order_id` VARCHAR(50) NOT NULL,
  `product_id` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL COMMENT '수량',
  PRIMARY KEY (`order_detail_id`),
  CONSTRAINT `fk_order_histories_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_histories_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '주문 내역';

CREATE INDEX `fk_order_histories_orders1_idx` ON `order_details` (`order_id` ASC) VISIBLE;

CREATE INDEX `fk_order_histories_products1_idx` ON `order_details` (`product_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
